Profiles:
  - name: "Ronnie Tiny Johan"
    assetID: "assets/images/Profile1.png"
  - name: "Douwe & Cornelia"
    assetID: "assets/images/Profile2.png"
  - name: "Roland"
    assetID: "assets/images/Profile3.png"
  - name: "Liset"
    assetID: "assets/images/Profile4.png"
  - name: "Jeroen"
    assetID: "assets/images/Profile5.png"

Highlights:
  - name: "Calito"
    video: "calito/calito.mp4"
    headerImage: "calito/IMG_3322.JPG"
    description: "tba"
    title: "tba"

Top:
  - name: "Calito"
    video: "calito/calito.mp4"
    headerImage: "calito/IMG_3322.JPG"
    description: "tba"
    title: "tba"
  - name: "Berlin"
    video: "berlin/Melvix_berlin.mp4"
    headerImage: "berlin/berlincover.png"
    description: "tba"
    title: "tba"

QuickContentPath: "quick_content/"