Profiles:
  - name: "Ronnie Tiny Johan"
    assetID: "assets/images/Profile1.png"
  - name: "Douwe & Cornelia"
    assetID: "assets/images/Profile2.png"
  - name: "Roland"
    assetID: "assets/images/Profile3.png"
  - name: "Liset"
    assetID: "assets/images/Profile4.png"
  - name: "Jeroen"
    assetID: "assets/images/Profile5.png"
    
QuickContentPath: "quick_content/"